/**
 * cb-mpc WebAssembly TypeScript wrapper.
 *
 * Provides a type-safe, ergonomic API over the raw Emscripten WASM module.
 * All opaque WASM pointers are wrapped in handle types and freed automatically
 * where possible.
 */

import type {
  CbMpcWasmModule,
  CurveHandle,
  PointHandle,
  Job2pHandle,
  JobMpHandle,
  Ecdsa2pKeyHandle,
  EcKeyMpHandle,
  PartySetHandle,
  DataTransport,
  Ecdsa2pKeyInfo,
  EcKeyMpInfo,
  EcPoint,
} from "./types";

export * from "./types";

// ---------------------------------------------------------------------------
// Module loader
// ---------------------------------------------------------------------------

// The Emscripten-generated factory function (imported at runtime).
// eslint-disable-next-line @typescript-eslint/no-var-requires
let createCbMpcFactory: (opts?: object) => Promise<CbMpcWasmModule>;

/**
 * Initialize the WASM module.
 *
 * @param wasmModuleFactory - The Emscripten module factory (from `require('./cbmpc.js')`
 *                            or `import('./cbmpc.js')`). If omitted, attempts dynamic import.
 * @returns A configured {@link CbMpc} instance ready for use.
 */
export async function initCbMpc(
  wasmModuleFactory?: (opts?: object) => Promise<CbMpcWasmModule>,
): Promise<CbMpc> {
  if (wasmModuleFactory) {
    createCbMpcFactory = wasmModuleFactory;
  } else if (!createCbMpcFactory) {
    // Dynamic import for the Emscripten glue
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore -- cbmpc.js is generated by Emscripten at build time
    const mod = await import(/* webpackIgnore: true */ "../cbmpc.js");
    createCbMpcFactory = mod.default || mod.createCbMpc || mod;
  }

  const wasm = await createCbMpcFactory();

  // Initialize transport callback registry on the module
  (wasm as CbMpcWasmModule)._transportCallbacks = {};

  return new CbMpc(wasm);
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Write a Uint8Array into WASM heap and return the pointer. Caller must free. */
function writeBytes(wasm: CbMpcWasmModule, data: Uint8Array): number {
  const ptr = wasm._malloc(data.length);
  wasm.HEAPU8.set(data, ptr);
  return ptr;
}

/** Read `size` bytes from WASM heap at `ptr` into a new Uint8Array. */
function readBytes(wasm: CbMpcWasmModule, ptr: number, size: number): Uint8Array {
  return new Uint8Array(wasm.HEAPU8.buffer, ptr, size).slice();
}

/** Allocate a cmem_t struct on the WASM heap and populate it. Returns pointer. */
function writeCmem(wasm: CbMpcWasmModule, data: Uint8Array): number {
  const cmemPtr = wasm._malloc(8); // cmem_t is {uint8_t* data, int size}
  const dataPtr = writeBytes(wasm, data);
  wasm.setValue(cmemPtr, dataPtr, "*");
  wasm.setValue(cmemPtr + 4, data.length, "i32");
  return cmemPtr;
}

/** Read a cmem_t from WASM heap and return its contents as Uint8Array. */
function readCmem(wasm: CbMpcWasmModule, cmemPtr: number): Uint8Array {
  const dataPtr = wasm.getValue(cmemPtr, "*");
  const size = wasm.getValue(cmemPtr + 4, "i32");
  if (!dataPtr || size <= 0) return new Uint8Array(0);
  return readBytes(wasm, dataPtr, size);
}

/** Free a cmem_t and its data buffer. */
function freeCmem(wasm: CbMpcWasmModule, cmemPtr: number): void {
  const dataPtr = wasm.getValue(cmemPtr, "*");
  if (dataPtr) wasm._free(dataPtr);
  wasm._free(cmemPtr);
}

/** Write a cmems_t (array of buffers) to the WASM heap. Returns pointer. */
function writeCmems(wasm: CbMpcWasmModule, buffers: Uint8Array[]): number {
  const count = buffers.length;
  let totalSize = 0;
  for (const b of buffers) totalSize += b.length;

  const dataPtr = wasm._malloc(totalSize);
  const sizesPtr = wasm._malloc(count * 4);
  let offset = 0;
  for (let i = 0; i < count; i++) {
    wasm.HEAPU8.set(buffers[i], dataPtr + offset);
    wasm.setValue(sizesPtr + i * 4, buffers[i].length, "i32");
    offset += buffers[i].length;
  }

  // cmems_t is {int count, uint8_t* data, int* sizes}
  const cmemsPtr = wasm._malloc(12);
  wasm.setValue(cmemsPtr, count, "i32");
  wasm.setValue(cmemsPtr + 4, dataPtr, "*");
  wasm.setValue(cmemsPtr + 8, sizesPtr, "*");
  return cmemsPtr;
}

/** Read a cmems_t from WASM heap into an array of Uint8Arrays. */
function readCmems(wasm: CbMpcWasmModule, cmemsPtr: number): Uint8Array[] {
  const count = wasm.getValue(cmemsPtr, "i32");
  const dataPtr = wasm.getValue(cmemsPtr + 4, "*");
  const sizesPtr = wasm.getValue(cmemsPtr + 8, "*");
  const result: Uint8Array[] = [];
  let offset = 0;
  for (let i = 0; i < count; i++) {
    const size = wasm.getValue(sizesPtr + i * 4, "i32");
    result.push(readBytes(wasm, dataPtr + offset, size));
    offset += size;
  }
  return result;
}

/** Free a cmems_t and its buffers. */
function freeCmems(wasm: CbMpcWasmModule, cmemsPtr: number): void {
  const dataPtr = wasm.getValue(cmemsPtr + 4, "*");
  const sizesPtr = wasm.getValue(cmemsPtr + 8, "*");
  if (dataPtr) wasm._free(dataPtr);
  if (sizesPtr) wasm._free(sizesPtr);
  wasm._free(cmemsPtr);
}

/** Allocate a ref struct (4 bytes, opaque pointer) and return its WASM address. */
function allocRef(wasm: CbMpcWasmModule): number {
  const ptr = wasm._malloc(4);
  wasm.setValue(ptr, 0, "*");
  return ptr;
}

/** Read the opaque pointer value from a ref struct. */
function readRef(wasm: CbMpcWasmModule, refPtr: number): number {
  return wasm.getValue(refPtr, "*");
}

/** Write a C string to WASM heap. Returns pointer. Caller must free. */
function writeCString(wasm: CbMpcWasmModule, str: string): number {
  const len = wasm.lengthBytesUTF8(str) + 1;
  const ptr = wasm._malloc(len);
  wasm.stringToUTF8(str, ptr, len);
  return ptr;
}

/** Check error code and throw if non-zero. */
function checkError(code: number, operation: string): void {
  if (code !== 0) {
    throw new CbMpcError(code, operation);
  }
}

// ---------------------------------------------------------------------------
// Error class
// ---------------------------------------------------------------------------

export class CbMpcError extends Error {
  constructor(
    public readonly code: number,
    public readonly operation: string,
  ) {
    super(`cb-mpc error ${code} during ${operation}`);
    this.name = "CbMpcError";
  }
}

// ---------------------------------------------------------------------------
// Transport ID management
// ---------------------------------------------------------------------------

let nextTransportId = 1;

// ---------------------------------------------------------------------------
// Main API class
// ---------------------------------------------------------------------------

export class CbMpc {
  /** @internal */
  constructor(private readonly wasm: CbMpcWasmModule) {}

  // =========================================================================
  // Curve operations
  // =========================================================================

  /**
   * Create a curve instance from an OpenSSL NID.
   * Caller must call {@link freeCurve} when done.
   */
  createCurve(curveCode: number): CurveHandle {
    const refPtr = allocRef(this.wasm);
    const ref = this.wasm.ccall("new_ecurve", "number", ["number"], [curveCode]) as number;
    this.wasm._free(refPtr);
    return ref as unknown as CurveHandle;
  }

  /** Free a curve handle. */
  freeCurve(handle: CurveHandle): void {
    // new_ecurve returns ecurve_ref by value (struct copy), need to write to stack
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, handle as unknown as number, "*");
    this.wasm.ccall("free_ecurve", null, ["number"], [refPtr]);
    this.wasm._free(refPtr);
  }

  /** Get the generator point of a curve. Caller must free the returned point. */
  curveGenerator(curve: CurveHandle): PointHandle {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, curve as unknown as number, "*");
    const point = this.wasm.ccall("ecurve_generator", "number", ["number"], [refPtr]) as number;
    this.wasm._free(refPtr);
    return point as unknown as PointHandle;
  }

  /** Get the order of the curve as big-endian bytes. */
  curveOrder(curve: CurveHandle): Uint8Array {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, curve as unknown as number, "*");
    const cmemPtr = this.wasm._malloc(8);
    // ecurve_order returns cmem_t by value; ccall can't handle that.
    // We'll call it directly and read the return value from the stack.
    const resultCmem = this.wasm.ccall("ecurve_order", "number", ["number"], [refPtr]);
    this.wasm._free(refPtr);
    // For struct returns, Emscripten uses a hidden sret pointer. Read the cmem_t.
    const dataPtr = this.wasm.getValue(resultCmem as number, "*");
    const size = this.wasm.getValue((resultCmem as number) + 4, "i32");
    const result = readBytes(this.wasm, dataPtr, size);
    this.wasm._free(dataPtr);
    this.wasm._free(cmemPtr);
    return result;
  }

  /** Get the OpenSSL NID of a curve. */
  curveCode(curve: CurveHandle): number {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, curve as unknown as number, "*");
    const code = this.wasm.ccall("ecurve_get_curve_code", "number", ["number"], [refPtr]) as number;
    this.wasm._free(refPtr);
    return code;
  }

  /** Generate a random scalar in the curve's field. */
  randomScalar(curve: CurveHandle): Uint8Array {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, curve as unknown as number, "*");
    const cmem = this.wasm.ccall("ecurve_random_scalar", "number", ["number"], [refPtr]) as number;
    this.wasm._free(refPtr);
    const dataPtr = this.wasm.getValue(cmem, "*");
    const size = this.wasm.getValue(cmem + 4, "i32");
    const result = readBytes(this.wasm, dataPtr, size);
    this.wasm._free(dataPtr);
    return result;
  }

  // =========================================================================
  // Point operations
  // =========================================================================

  /** Deserialize a point from bytes. Caller must free. */
  pointFromBytes(data: Uint8Array): PointHandle {
    const cmemPtr = writeCmem(this.wasm, data);
    // ecc_point_from_bytes takes cmem_t by value (8 bytes on stack)
    const dataFieldPtr = this.wasm.getValue(cmemPtr, "*");
    const sizeField = this.wasm.getValue(cmemPtr + 4, "i32");
    const point = this.wasm.ccall(
      "ecc_point_from_bytes",
      "number",
      ["number", "number"],
      [dataFieldPtr, sizeField],
    ) as number;
    freeCmem(this.wasm, cmemPtr);
    return point as unknown as PointHandle;
  }

  /** Serialize a point to bytes. */
  pointToBytes(point: PointHandle): Uint8Array {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, point as unknown as number, "*");
    const cmem = this.wasm.ccall("ecc_point_to_bytes", "number", ["number"], [refPtr]) as number;
    this.wasm._free(refPtr);
    const dataPtr = this.wasm.getValue(cmem, "*");
    const size = this.wasm.getValue(cmem + 4, "i32");
    const result = readBytes(this.wasm, dataPtr, size);
    this.wasm._free(dataPtr);
    return result;
  }

  /** Get the X coordinate of a point. */
  pointGetX(point: PointHandle): Uint8Array {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, point as unknown as number, "*");
    const cmem = this.wasm.ccall("ecc_point_get_x", "number", ["number"], [refPtr]) as number;
    this.wasm._free(refPtr);
    const dataPtr = this.wasm.getValue(cmem, "*");
    const size = this.wasm.getValue(cmem + 4, "i32");
    const result = readBytes(this.wasm, dataPtr, size);
    this.wasm._free(dataPtr);
    return result;
  }

  /** Get the Y coordinate of a point. */
  pointGetY(point: PointHandle): Uint8Array {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, point as unknown as number, "*");
    const cmem = this.wasm.ccall("ecc_point_get_y", "number", ["number"], [refPtr]) as number;
    this.wasm._free(refPtr);
    const dataPtr = this.wasm.getValue(cmem, "*");
    const size = this.wasm.getValue(cmem + 4, "i32");
    const result = readBytes(this.wasm, dataPtr, size);
    this.wasm._free(dataPtr);
    return result;
  }

  /** Get both coordinates of a point. */
  pointCoordinates(point: PointHandle): EcPoint {
    return {
      x: this.pointGetX(point),
      y: this.pointGetY(point),
    };
  }

  /** Scalar multiplication: scalar * point. Caller must free returned point. */
  pointMultiply(point: PointHandle, scalar: Uint8Array): PointHandle {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, point as unknown as number, "*");
    const cmemPtr = writeCmem(this.wasm, scalar);
    const dataFieldPtr = this.wasm.getValue(cmemPtr, "*");
    const sizeField = this.wasm.getValue(cmemPtr + 4, "i32");
    const result = this.wasm.ccall(
      "ecc_point_multiply",
      "number",
      ["number", "number", "number"],
      [refPtr, dataFieldPtr, sizeField],
    ) as number;
    this.wasm._free(refPtr);
    freeCmem(this.wasm, cmemPtr);
    return result as unknown as PointHandle;
  }

  /** Point addition. Caller must free returned point. */
  pointAdd(p1: PointHandle, p2: PointHandle): PointHandle {
    const ref1 = this.wasm._malloc(4);
    const ref2 = this.wasm._malloc(4);
    this.wasm.setValue(ref1, p1 as unknown as number, "*");
    this.wasm.setValue(ref2, p2 as unknown as number, "*");
    const result = this.wasm.ccall(
      "ecc_point_add",
      "number",
      ["number", "number"],
      [ref1, ref2],
    ) as number;
    this.wasm._free(ref1);
    this.wasm._free(ref2);
    return result as unknown as PointHandle;
  }

  /** Point subtraction. Caller must free returned point. */
  pointSubtract(p1: PointHandle, p2: PointHandle): PointHandle {
    const ref1 = this.wasm._malloc(4);
    const ref2 = this.wasm._malloc(4);
    this.wasm.setValue(ref1, p1 as unknown as number, "*");
    this.wasm.setValue(ref2, p2 as unknown as number, "*");
    const result = this.wasm.ccall(
      "ecc_point_subtract",
      "number",
      ["number", "number"],
      [ref1, ref2],
    ) as number;
    this.wasm._free(ref1);
    this.wasm._free(ref2);
    return result as unknown as PointHandle;
  }

  /** Check if a point is the point at infinity. */
  pointIsZero(point: PointHandle): boolean {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, point as unknown as number, "*");
    const result = this.wasm.ccall("ecc_point_is_zero", "number", ["number"], [refPtr]) as number;
    this.wasm._free(refPtr);
    return result === 1;
  }

  /** Check if two points are equal. */
  pointEquals(p1: PointHandle, p2: PointHandle): boolean {
    const ref1 = this.wasm._malloc(4);
    const ref2 = this.wasm._malloc(4);
    this.wasm.setValue(ref1, p1 as unknown as number, "*");
    this.wasm.setValue(ref2, p2 as unknown as number, "*");
    const result = this.wasm.ccall(
      "ecc_point_equals",
      "number",
      ["number", "number"],
      [ref1, ref2],
    ) as number;
    this.wasm._free(ref1);
    this.wasm._free(ref2);
    return result === 1;
  }

  /** Free a point handle. */
  freePoint(point: PointHandle): void {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, point as unknown as number, "*");
    this.wasm.ccall("free_ecc_point", null, ["number"], [refPtr]);
    this.wasm._free(refPtr);
  }

  /** Multiply the curve generator by a scalar. Caller must free returned point. */
  mulGenerator(curve: CurveHandle, scalar: Uint8Array): PointHandle {
    const curveRef = this.wasm._malloc(4);
    this.wasm.setValue(curveRef, curve as unknown as number, "*");
    const cmemPtr = writeCmem(this.wasm, scalar);
    const dataFieldPtr = this.wasm.getValue(cmemPtr, "*");
    const sizeField = this.wasm.getValue(cmemPtr + 4, "i32");
    const result = this.wasm.ccall(
      "ecurve_mul_generator",
      "number",
      ["number", "number", "number"],
      [curveRef, dataFieldPtr, sizeField],
    ) as number;
    this.wasm._free(curveRef);
    freeCmem(this.wasm, cmemPtr);
    return result as unknown as PointHandle;
  }

  /**
   * Verify an ECDSA signature (DER-encoded).
   * @returns true if valid.
   */
  verifyDer(
    curveCode: number,
    publicKeyOct: Uint8Array,
    hash: Uint8Array,
    derSig: Uint8Array,
  ): boolean {
    const pubPtr = writeCmem(this.wasm, publicKeyOct);
    const hashPtr = writeCmem(this.wasm, hash);
    const sigPtr = writeCmem(this.wasm, derSig);

    const result = this.wasm.ccall(
      "ecc_verify_der",
      "number",
      ["number", "number", "number", "number", "number", "number", "number"],
      [
        curveCode,
        this.wasm.getValue(pubPtr, "*"), this.wasm.getValue(pubPtr + 4, "i32"),
        this.wasm.getValue(hashPtr, "*"), this.wasm.getValue(hashPtr + 4, "i32"),
        this.wasm.getValue(sigPtr, "*"), this.wasm.getValue(sigPtr + 4, "i32"),
      ],
    ) as number;

    freeCmem(this.wasm, pubPtr);
    freeCmem(this.wasm, hashPtr);
    freeCmem(this.wasm, sigPtr);
    return result === 0;
  }

  // =========================================================================
  // Scalar operations
  // =========================================================================

  /** Add two big-number scalars (a + b). */
  bnAdd(a: Uint8Array, b: Uint8Array): Uint8Array {
    const cmemA = writeCmem(this.wasm, a);
    const cmemB = writeCmem(this.wasm, b);
    const result = this.wasm.ccall(
      "bn_add",
      "number",
      ["number", "number", "number", "number"],
      [
        this.wasm.getValue(cmemA, "*"), this.wasm.getValue(cmemA + 4, "i32"),
        this.wasm.getValue(cmemB, "*"), this.wasm.getValue(cmemB + 4, "i32"),
      ],
    ) as number;
    const dataPtr = this.wasm.getValue(result, "*");
    const size = this.wasm.getValue(result + 4, "i32");
    const out = readBytes(this.wasm, dataPtr, size);
    this.wasm._free(dataPtr);
    freeCmem(this.wasm, cmemA);
    freeCmem(this.wasm, cmemB);
    return out;
  }

  /** Modular addition (a + b) mod curve_order. */
  ecModAdd(curve: CurveHandle, a: Uint8Array, b: Uint8Array): Uint8Array {
    const curveRef = this.wasm._malloc(4);
    this.wasm.setValue(curveRef, curve as unknown as number, "*");
    const cmemA = writeCmem(this.wasm, a);
    const cmemB = writeCmem(this.wasm, b);
    const result = this.wasm.ccall(
      "ec_mod_add",
      "number",
      ["number", "number", "number", "number", "number"],
      [
        curveRef,
        this.wasm.getValue(cmemA, "*"), this.wasm.getValue(cmemA + 4, "i32"),
        this.wasm.getValue(cmemB, "*"), this.wasm.getValue(cmemB + 4, "i32"),
      ],
    ) as number;
    const dataPtr = this.wasm.getValue(result, "*");
    const size = this.wasm.getValue(result + 4, "i32");
    const out = readBytes(this.wasm, dataPtr, size);
    this.wasm._free(dataPtr);
    this.wasm._free(curveRef);
    freeCmem(this.wasm, cmemA);
    freeCmem(this.wasm, cmemB);
    return out;
  }

  // =========================================================================
  // Transport management (internal)
  // =========================================================================

  /** @internal Register a transport and return its ID. */
  private registerTransport(transport: DataTransport): number {
    const id = nextTransportId++;
    this.wasm._transportCallbacks[id] = transport;
    return id;
  }

  /** @internal Unregister a transport. */
  private unregisterTransport(id: number): void {
    delete this.wasm._transportCallbacks[id];
  }

  // =========================================================================
  // ECDSA Two-Party Protocol
  // =========================================================================

  /**
   * Two-party ECDSA distributed key generation.
   *
   * @param transport  - Network transport for message passing.
   * @param partyIndex - This party's index (0 or 1).
   * @param partyNames - Names for both parties [party0Name, party1Name].
   * @param curveCode  - OpenSSL NID for the curve (e.g., NID_secp256k1).
   * @returns Handle to the generated key share. Caller must free with {@link freeEcdsa2pKey}.
   */
  async ecdsa2pDkg(
    transport: DataTransport,
    partyIndex: number,
    partyNames: [string, string],
    curveCode: number,
  ): Promise<Ecdsa2pKeyHandle> {
    const transportId = this.registerTransport(transport);
    const name0 = writeCString(this.wasm, partyNames[0]);
    const name1 = writeCString(this.wasm, partyNames[1]);

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_2p",
        "number",
        ["number", "number", "number", "number"],
        [transportId, partyIndex, name0, name1],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "ecdsa2pDkg: failed to create job");

      const keyRef = allocRef(this.wasm);
      const err = await this.wasm.ccall(
        "mpc_ecdsa2p_dkg",
        "number",
        ["number", "number", "number"],
        [jobPtr, curveCode, keyRef],
        { async: true },
      ) as number;

      const keyHandle = readRef(this.wasm, keyRef) as unknown as Ecdsa2pKeyHandle;
      this.wasm._free(keyRef);
      this.wasm.ccall("free_job_2p", null, ["number"], [jobPtr]);

      checkError(err, "ecdsa2pDkg");
      return keyHandle;
    } finally {
      this.wasm._free(name0);
      this.wasm._free(name1);
      this.unregisterTransport(transportId);
    }
  }

  /**
   * Two-party ECDSA signing.
   *
   * @param transport  - Network transport for message passing.
   * @param partyIndex - This party's index (0 or 1).
   * @param partyNames - Names for both parties.
   * @param key        - Key handle from DKG.
   * @param sessionId  - Unique session identifier for this signing session.
   * @param messages   - Messages (hashes) to sign.
   * @returns Array of DER-encoded signatures, one per message.
   */
  async ecdsa2pSign(
    transport: DataTransport,
    partyIndex: number,
    partyNames: [string, string],
    key: Ecdsa2pKeyHandle,
    sessionId: Uint8Array,
    messages: Uint8Array[],
  ): Promise<Uint8Array[]> {
    const transportId = this.registerTransport(transport);
    const name0 = writeCString(this.wasm, partyNames[0]);
    const name1 = writeCString(this.wasm, partyNames[1]);

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_2p",
        "number",
        ["number", "number", "number", "number"],
        [transportId, partyIndex, name0, name1],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "ecdsa2pSign: failed to create job");

      const sidCmem = writeCmem(this.wasm, sessionId);
      const keyRef = this.wasm._malloc(4);
      this.wasm.setValue(keyRef, key as unknown as number, "*");
      const msgsCmems = writeCmems(this.wasm, messages);
      const sigsCmems = this.wasm._malloc(12); // cmems_t output

      const err = await this.wasm.ccall(
        "mpc_ecdsa2p_sign",
        "number",
        ["number", "number", "number", "number", "number"],
        [jobPtr, sidCmem, keyRef, msgsCmems, sigsCmems],
        { async: true },
      ) as number;

      const sigs = err === 0 ? readCmems(this.wasm, sigsCmems) : [];

      // Cleanup
      this.wasm._free(keyRef);
      freeCmem(this.wasm, sidCmem);
      freeCmems(this.wasm, msgsCmems);
      freeCmems(this.wasm, sigsCmems);
      this.wasm.ccall("free_job_2p", null, ["number"], [jobPtr]);

      checkError(err, "ecdsa2pSign");
      return sigs;
    } finally {
      this.wasm._free(name0);
      this.wasm._free(name1);
      this.unregisterTransport(transportId);
    }
  }

  /**
   * Two-party ECDSA key refresh.
   *
   * @returns New key handle. The old key remains valid until freed.
   */
  async ecdsa2pRefresh(
    transport: DataTransport,
    partyIndex: number,
    partyNames: [string, string],
    key: Ecdsa2pKeyHandle,
  ): Promise<Ecdsa2pKeyHandle> {
    const transportId = this.registerTransport(transport);
    const name0 = writeCString(this.wasm, partyNames[0]);
    const name1 = writeCString(this.wasm, partyNames[1]);

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_2p",
        "number",
        ["number", "number", "number", "number"],
        [transportId, partyIndex, name0, name1],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "ecdsa2pRefresh: failed to create job");

      const keyRef = this.wasm._malloc(4);
      this.wasm.setValue(keyRef, key as unknown as number, "*");
      const newKeyRef = allocRef(this.wasm);

      const err = await this.wasm.ccall(
        "mpc_ecdsa2p_refresh",
        "number",
        ["number", "number", "number"],
        [jobPtr, keyRef, newKeyRef],
        { async: true },
      ) as number;

      const newKey = readRef(this.wasm, newKeyRef) as unknown as Ecdsa2pKeyHandle;

      this.wasm._free(keyRef);
      this.wasm._free(newKeyRef);
      this.wasm.ccall("free_job_2p", null, ["number"], [jobPtr]);

      checkError(err, "ecdsa2pRefresh");
      return newKey;
    } finally {
      this.wasm._free(name0);
      this.wasm._free(name1);
      this.unregisterTransport(transportId);
    }
  }

  /** Get key information from a two-party ECDSA key handle. */
  ecdsa2pKeyInfo(key: Ecdsa2pKeyHandle): Ecdsa2pKeyInfo {
    const keyRef = this.wasm._malloc(4);
    this.wasm.setValue(keyRef, key as unknown as number, "*");

    const roleIndex = this.wasm.ccall(
      "mpc_ecdsa2p_key_get_role_index", "number", ["number"], [keyRef],
    ) as number;

    const curveCode = this.wasm.ccall(
      "mpc_ecdsa2p_key_get_curve_code", "number", ["number"], [keyRef],
    ) as number;

    // Get public key Q
    const qHandle = this.wasm.ccall(
      "mpc_ecdsa2p_key_get_Q", "number", ["number"], [keyRef],
    ) as number;
    const qRef = this.wasm._malloc(4);
    this.wasm.setValue(qRef, qHandle, "*");
    const qCmem = this.wasm.ccall("ecc_point_to_bytes", "number", ["number"], [qRef]) as number;
    const qDataPtr = this.wasm.getValue(qCmem, "*");
    const qSize = this.wasm.getValue(qCmem + 4, "i32");
    const publicKey = readBytes(this.wasm, qDataPtr, qSize);
    this.wasm._free(qDataPtr);
    this.wasm._free(qRef);
    // Free the point copy
    const freeRef = this.wasm._malloc(4);
    this.wasm.setValue(freeRef, qHandle, "*");
    this.wasm.ccall("free_ecc_point", null, ["number"], [freeRef]);
    this.wasm._free(freeRef);

    // Get x_share
    const xCmem = this.wasm.ccall(
      "mpc_ecdsa2p_key_get_x_share", "number", ["number"], [keyRef],
    ) as number;
    const xDataPtr = this.wasm.getValue(xCmem, "*");
    const xSize = this.wasm.getValue(xCmem + 4, "i32");
    const xShare = readBytes(this.wasm, xDataPtr, xSize);
    this.wasm._free(xDataPtr);

    this.wasm._free(keyRef);

    return { roleIndex, curveCode, publicKey, xShare };
  }

  /** Free a two-party ECDSA key handle. */
  freeEcdsa2pKey(key: Ecdsa2pKeyHandle): void {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, key as unknown as number, "*");
    this.wasm.ccall("free_mpc_ecdsa2p_key", null, ["number"], [refPtr]);
    this.wasm._free(refPtr);
  }

  // =========================================================================
  // EC Key Multi-Party Protocol
  // =========================================================================

  /**
   * Multi-party EC distributed key generation.
   *
   * @param transport   - Network transport.
   * @param partyCount  - Total number of parties.
   * @param partyIndex  - This party's index.
   * @param partyNames  - Names for all parties.
   * @param curve       - Curve handle.
   * @returns Key handle. Caller must free with {@link freeEcKeyMp}.
   */
  async ecKeyMpDkg(
    transport: DataTransport,
    partyCount: number,
    partyIndex: number,
    partyNames: string[],
    curve: CurveHandle,
  ): Promise<EcKeyMpHandle> {
    const transportId = this.registerTransport(transport);
    const namesPtrs = partyNames.map((n) => writeCString(this.wasm, n));
    const namesArray = this.wasm._malloc(namesPtrs.length * 4);
    for (let i = 0; i < namesPtrs.length; i++) {
      this.wasm.setValue(namesArray + i * 4, namesPtrs[i], "*");
    }

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_mp",
        "number",
        ["number", "number", "number", "number", "number"],
        [transportId, partyCount, partyIndex, namesArray, partyNames.length],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "ecKeyMpDkg: failed to create job");

      const curveRef = this.wasm._malloc(4);
      this.wasm.setValue(curveRef, curve as unknown as number, "*");
      const keyRef = allocRef(this.wasm);

      const err = await this.wasm.ccall(
        "mpc_eckey_mp_dkg",
        "number",
        ["number", "number", "number"],
        [jobPtr, curveRef, keyRef],
        { async: true },
      ) as number;

      const keyHandle = readRef(this.wasm, keyRef) as unknown as EcKeyMpHandle;
      this.wasm._free(curveRef);
      this.wasm._free(keyRef);
      this.wasm.ccall("free_job_mp", null, ["number"], [jobPtr]);

      checkError(err, "ecKeyMpDkg");
      return keyHandle;
    } finally {
      for (const p of namesPtrs) this.wasm._free(p);
      this.wasm._free(namesArray);
      this.unregisterTransport(transportId);
    }
  }

  /**
   * Multi-party EC key refresh.
   */
  async ecKeyMpRefresh(
    transport: DataTransport,
    partyCount: number,
    partyIndex: number,
    partyNames: string[],
    key: EcKeyMpHandle,
    sessionId: Uint8Array,
  ): Promise<EcKeyMpHandle> {
    const transportId = this.registerTransport(transport);
    const namesPtrs = partyNames.map((n) => writeCString(this.wasm, n));
    const namesArray = this.wasm._malloc(namesPtrs.length * 4);
    for (let i = 0; i < namesPtrs.length; i++) {
      this.wasm.setValue(namesArray + i * 4, namesPtrs[i], "*");
    }

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_mp",
        "number",
        ["number", "number", "number", "number", "number"],
        [transportId, partyCount, partyIndex, namesArray, partyNames.length],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "ecKeyMpRefresh: failed to create job");

      const keyRef = this.wasm._malloc(4);
      this.wasm.setValue(keyRef, key as unknown as number, "*");
      const sidCmem = writeCmem(this.wasm, sessionId);
      const newKeyRef = allocRef(this.wasm);

      const err = await this.wasm.ccall(
        "mpc_eckey_mp_refresh",
        "number",
        ["number", "number", "number", "number"],
        [jobPtr, sidCmem, keyRef, newKeyRef],
        { async: true },
      ) as number;

      const newKey = readRef(this.wasm, newKeyRef) as unknown as EcKeyMpHandle;
      this.wasm._free(keyRef);
      this.wasm._free(newKeyRef);
      freeCmem(this.wasm, sidCmem);
      this.wasm.ccall("free_job_mp", null, ["number"], [jobPtr]);

      checkError(err, "ecKeyMpRefresh");
      return newKey;
    } finally {
      for (const p of namesPtrs) this.wasm._free(p);
      this.wasm._free(namesArray);
      this.unregisterTransport(transportId);
    }
  }

  /** Get key information from a multi-party EC key handle. */
  ecKeyMpInfo(key: EcKeyMpHandle): EcKeyMpInfo {
    const keyRef = this.wasm._malloc(4);
    this.wasm.setValue(keyRef, key as unknown as number, "*");

    // Party name
    const nameCmem = this.wasm._malloc(8);
    this.wasm.ccall("mpc_eckey_mp_get_party_name", "number", ["number", "number"], [keyRef, nameCmem]);
    const nameData = readCmem(this.wasm, nameCmem);
    const partyName = new TextDecoder().decode(nameData);
    freeCmem(this.wasm, nameCmem);

    // Public key Q
    const qHandle = this.wasm.ccall("mpc_eckey_mp_get_Q", "number", ["number"], [keyRef]) as number;
    const qRef = this.wasm._malloc(4);
    this.wasm.setValue(qRef, qHandle, "*");
    const qCmem = this.wasm.ccall("ecc_point_to_bytes", "number", ["number"], [qRef]) as number;
    const qDataPtr = this.wasm.getValue(qCmem, "*");
    const qSize = this.wasm.getValue(qCmem + 4, "i32");
    const publicKey = readBytes(this.wasm, qDataPtr, qSize);
    this.wasm._free(qDataPtr);
    this.wasm._free(qRef);
    const freeRef = this.wasm._malloc(4);
    this.wasm.setValue(freeRef, qHandle, "*");
    this.wasm.ccall("free_ecc_point", null, ["number"], [freeRef]);
    this.wasm._free(freeRef);

    // x_share
    const xCmem = this.wasm._malloc(8);
    this.wasm.ccall("mpc_eckey_mp_get_x_share", "number", ["number", "number"], [keyRef, xCmem]);
    const xShare = readCmem(this.wasm, xCmem);
    freeCmem(this.wasm, xCmem);

    this.wasm._free(keyRef);

    return { partyName, publicKey, xShare };
  }

  /** Serialize a multi-party EC key to bytes. */
  serializeEcKeyMp(key: EcKeyMpHandle): Uint8Array[] {
    const keyRef = this.wasm._malloc(4);
    this.wasm.setValue(keyRef, key as unknown as number, "*");
    const serCmems = this.wasm._malloc(12);

    const err = this.wasm.ccall(
      "serialize_mpc_eckey_mp", "number", ["number", "number"], [keyRef, serCmems],
    ) as number;

    const result = err === 0 ? readCmems(this.wasm, serCmems) : [];
    freeCmems(this.wasm, serCmems);
    this.wasm._free(keyRef);
    checkError(err, "serializeEcKeyMp");
    return result;
  }

  /** Deserialize a multi-party EC key from bytes. */
  deserializeEcKeyMp(data: Uint8Array[]): EcKeyMpHandle {
    const serCmems = writeCmems(this.wasm, data);
    const keyRef = allocRef(this.wasm);

    const err = this.wasm.ccall(
      "deserialize_mpc_eckey_mp", "number", ["number", "number"], [serCmems, keyRef],
    ) as number;

    const keyHandle = readRef(this.wasm, keyRef) as unknown as EcKeyMpHandle;
    this.wasm._free(keyRef);
    freeCmems(this.wasm, serCmems);
    checkError(err, "deserializeEcKeyMp");
    return keyHandle;
  }

  /** Free a multi-party EC key handle. */
  freeEcKeyMp(key: EcKeyMpHandle): void {
    const refPtr = this.wasm._malloc(4);
    this.wasm.setValue(refPtr, key as unknown as number, "*");
    this.wasm.ccall("free_mpc_eckey_mp", null, ["number"], [refPtr]);
    this.wasm._free(refPtr);
  }

  // =========================================================================
  // ECDSA Multi-Party Signing
  // =========================================================================

  /**
   * Multi-party ECDSA signing.
   *
   * @param transport   - Network transport.
   * @param partyCount  - Total number of parties.
   * @param partyIndex  - This party's index.
   * @param partyNames  - Names for all parties.
   * @param key         - EC key handle from DKG.
   * @param message     - Message hash to sign.
   * @param sigReceiver - Party index that receives the final signature (-1 for all).
   * @returns DER-encoded signature (empty for non-receivers).
   */
  async ecdsaMpSign(
    transport: DataTransport,
    partyCount: number,
    partyIndex: number,
    partyNames: string[],
    key: EcKeyMpHandle,
    message: Uint8Array,
    sigReceiver: number,
  ): Promise<Uint8Array> {
    const transportId = this.registerTransport(transport);
    const namesPtrs = partyNames.map((n) => writeCString(this.wasm, n));
    const namesArray = this.wasm._malloc(namesPtrs.length * 4);
    for (let i = 0; i < namesPtrs.length; i++) {
      this.wasm.setValue(namesArray + i * 4, namesPtrs[i], "*");
    }

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_mp",
        "number",
        ["number", "number", "number", "number", "number"],
        [transportId, partyCount, partyIndex, namesArray, partyNames.length],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "ecdsaMpSign: failed to create job");

      const keyRef = this.wasm._malloc(4);
      this.wasm.setValue(keyRef, key as unknown as number, "*");
      const msgCmem = writeCmem(this.wasm, message);
      const sigCmem = this.wasm._malloc(8);

      const err = await this.wasm.ccall(
        "mpc_ecdsampc_sign",
        "number",
        ["number", "number", "number", "number", "number"],
        [jobPtr, keyRef, msgCmem, sigReceiver, sigCmem],
        { async: true },
      ) as number;

      const sig = err === 0 ? readCmem(this.wasm, sigCmem) : new Uint8Array(0);

      this.wasm._free(keyRef);
      freeCmem(this.wasm, msgCmem);
      freeCmem(this.wasm, sigCmem);
      this.wasm.ccall("free_job_mp", null, ["number"], [jobPtr]);

      checkError(err, "ecdsaMpSign");
      return sig;
    } finally {
      for (const p of namesPtrs) this.wasm._free(p);
      this.wasm._free(namesArray);
      this.unregisterTransport(transportId);
    }
  }

  // =========================================================================
  // EdDSA Multi-Party Signing
  // =========================================================================

  /**
   * Multi-party EdDSA signing.
   *
   * @param transport   - Network transport.
   * @param partyCount  - Total number of parties.
   * @param partyIndex  - This party's index.
   * @param partyNames  - Names for all parties.
   * @param key         - EC key handle from DKG.
   * @param message     - Message to sign.
   * @param sigReceiver - Party index that receives the final signature.
   * @returns EdDSA signature bytes (empty for non-receivers).
   */
  async eddsaMpSign(
    transport: DataTransport,
    partyCount: number,
    partyIndex: number,
    partyNames: string[],
    key: EcKeyMpHandle,
    message: Uint8Array,
    sigReceiver: number,
  ): Promise<Uint8Array> {
    const transportId = this.registerTransport(transport);
    const namesPtrs = partyNames.map((n) => writeCString(this.wasm, n));
    const namesArray = this.wasm._malloc(namesPtrs.length * 4);
    for (let i = 0; i < namesPtrs.length; i++) {
      this.wasm.setValue(namesArray + i * 4, namesPtrs[i], "*");
    }

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_mp",
        "number",
        ["number", "number", "number", "number", "number"],
        [transportId, partyCount, partyIndex, namesArray, partyNames.length],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "eddsaMpSign: failed to create job");

      const keyRef = this.wasm._malloc(4);
      this.wasm.setValue(keyRef, key as unknown as number, "*");
      const msgCmem = writeCmem(this.wasm, message);
      const sigCmem = this.wasm._malloc(8);

      const err = await this.wasm.ccall(
        "mpc_eddsampc_sign",
        "number",
        ["number", "number", "number", "number", "number"],
        [jobPtr, keyRef, msgCmem, sigReceiver, sigCmem],
        { async: true },
      ) as number;

      const sig = err === 0 ? readCmem(this.wasm, sigCmem) : new Uint8Array(0);

      this.wasm._free(keyRef);
      freeCmem(this.wasm, msgCmem);
      freeCmem(this.wasm, sigCmem);
      this.wasm.ccall("free_job_mp", null, ["number"], [jobPtr]);

      checkError(err, "eddsaMpSign");
      return sig;
    } finally {
      for (const p of namesPtrs) this.wasm._free(p);
      this.wasm._free(namesArray);
      this.unregisterTransport(transportId);
    }
  }

  // =========================================================================
  // Zero-Knowledge Proofs
  // =========================================================================

  /**
   * Generate a ZK discrete-log proof.
   *
   * @param Q         - Public key point handle.
   * @param witness   - Secret witness (scalar bytes).
   * @param sessionId - Session identifier.
   * @param aux       - Auxiliary data (uint64).
   * @returns Proof bytes.
   */
  async zkDlProve(
    Q: PointHandle,
    witness: Uint8Array,
    sessionId: Uint8Array,
    aux: number,
  ): Promise<Uint8Array> {
    const qRef = this.wasm._malloc(4);
    this.wasm.setValue(qRef, Q as unknown as number, "*");
    const wCmem = writeCmem(this.wasm, witness);
    const sidCmem = writeCmem(this.wasm, sessionId);
    const proofCmem = this.wasm._malloc(8);

    const err = await this.wasm.ccall(
      "zk_dl_prove",
      "number",
      ["number", "number", "number", "number", "number"],
      [qRef, wCmem, sidCmem, aux, proofCmem],
      { async: true },
    ) as number;

    const proof = err === 0 ? readCmem(this.wasm, proofCmem) : new Uint8Array(0);

    this.wasm._free(qRef);
    freeCmem(this.wasm, wCmem);
    freeCmem(this.wasm, sidCmem);
    freeCmem(this.wasm, proofCmem);

    checkError(err, "zkDlProve");
    return proof;
  }

  /**
   * Verify a ZK discrete-log proof.
   *
   * @param Q         - Public key point handle.
   * @param proof     - Proof bytes (from zkDlProve).
   * @param sessionId - Session identifier (must match prover's).
   * @param aux       - Auxiliary data (must match prover's).
   * @returns true if the proof is valid.
   */
  async zkDlVerify(
    Q: PointHandle,
    proof: Uint8Array,
    sessionId: Uint8Array,
    aux: number,
  ): Promise<boolean> {
    const qRef = this.wasm._malloc(4);
    this.wasm.setValue(qRef, Q as unknown as number, "*");
    const proofCmem = writeCmem(this.wasm, proof);
    const sidCmem = writeCmem(this.wasm, sessionId);

    const result = await this.wasm.ccall(
      "zk_dl_verify",
      "number",
      ["number", "number", "number", "number"],
      [qRef, proofCmem, sidCmem, aux],
      { async: true },
    ) as number;

    this.wasm._free(qRef);
    freeCmem(this.wasm, proofCmem);
    freeCmem(this.wasm, sidCmem);

    return result === 0;
  }

  // =========================================================================
  // Agree Random (Two-Party)
  // =========================================================================

  /**
   * Two-party agreed random value generation.
   *
   * @param transport  - Network transport.
   * @param partyIndex - This party's index (0 or 1).
   * @param partyNames - Names for both parties.
   * @param bitLen     - Bit length of the random value.
   * @returns Random bytes agreed upon by both parties.
   */
  async agreeRandom(
    transport: DataTransport,
    partyIndex: number,
    partyNames: [string, string],
    bitLen: number,
  ): Promise<Uint8Array> {
    const transportId = this.registerTransport(transport);
    const name0 = writeCString(this.wasm, partyNames[0]);
    const name1 = writeCString(this.wasm, partyNames[1]);

    try {
      const jobPtr = this.wasm.ccall(
        "wasm_new_job_2p",
        "number",
        ["number", "number", "number", "number"],
        [transportId, partyIndex, name0, name1],
      ) as number;

      if (!jobPtr) throw new CbMpcError(-1, "agreeRandom: failed to create job");

      const outCmem = this.wasm._malloc(8);

      const err = await this.wasm.ccall(
        "mpc_agree_random",
        "number",
        ["number", "number", "number"],
        [jobPtr, bitLen, outCmem],
        { async: true },
      ) as number;

      const result = err === 0 ? readCmem(this.wasm, outCmem) : new Uint8Array(0);

      freeCmem(this.wasm, outCmem);
      this.wasm.ccall("free_job_2p", null, ["number"], [jobPtr]);

      checkError(err, "agreeRandom");
      return result;
    } finally {
      this.wasm._free(name0);
      this.wasm._free(name1);
      this.unregisterTransport(transportId);
    }
  }
}
